#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀✨ Running pre-push hook"

# Build the app
echo "🚀✨ Building the app before push... 🔨📦"
if ! npm run build; then
  echo "❌⛔ Build failed. 🔍 Please fix the errors before pushing. 🛠️"
  exit 1
fi

# Lint and fix staged files
echo "🔍 Running lint-staged to format/lint staged files..."
npx lint-staged
